/**
 * Fictional sample data for prototype / user-testing use.
 *
 * Generated by the `inject-dummy-data` skill — see
 * `.claude/skills/inject-dummy-data/SKILL.md`. Re-running the skill overwrites
 * this directory, so put prototype-specific mapping in your own files (or in
 * `adapters.ts`, which the skill leaves alone once it exists).
 *
 * Every person, property, listing, phone number and email below is invented.
 * Phones use the fictional 555 block; emails use `example.com` (RFC 2606), so a
 * user-testing participant who taps one cannot reach a real person.
 */

import raw from './sample-data.json'

// ─── Types ────────────────────────────────────────────────────────────────────

export type ListingStatus =
  | 'New'
  | 'Active'
  | 'Price Change'
  | 'Coming Soon'
  | 'Closed'

export type ClientStatus =
  | 'Active'
  | 'Requests'
  | 'Invited'
  | 'Shared'
  | 'Archived'

export type TourState = 'Upcoming' | 'Past'

export type TourStopStatus = 'Confirmed' | 'Requested' | 'No status'

export interface SampleMeta {
  description: string
  version: string
  recordsPerType: number
  notice: string
}

export interface Agent {
  id: string
  firstName: string
  lastName: string
  title: string
  brokerage: string
  email: string
  phone: string
  avatar: string
  license: string
}

export interface Client {
  id: string
  displayName: string
  members: string[]
  initials: string[]
  status: ClientStatus
  lastSeen: string
  agentId: string
  savedCount: number
  tourRequestCount: number
  email: string
  phone: string
  avatar: string
}

export interface SearchCriteria {
  location: string
  propertyType?: string
  priceMin?: number
  priceMax?: number
  bedsMin?: number
  bathsMin?: number
  parkingMin?: number
  keywords?: string
  features?: string[]
  status?: string[]
  openHouseOnly?: boolean
}

export interface SavedSearch {
  id: string
  name: string
  /** A client id, or the literal `'agent'` for the logged-in agent's own search. */
  savedBy: string
  criteria: SearchCriteria
}

export interface Address {
  line1: string
  city: string
  state: string
  zip: string
}

export interface PricePoint {
  price: number
}

export interface Listing {
  id: string
  mlsId: string
  status: ListingStatus
  daysOnMarket: number
  price: number
  /** Empty for listings that have never repriced. Oldest first. */
  priceHistory: PricePoint[]
  beds: number
  bathsFull: number
  bathsHalf: number
  /** `null` where the source has no square footage (e.g. the duplex). */
  sqft: number | null
  parking: string
  /** Multi-unit properties only. */
  units?: number
  propertyType: string
  address: Address
  photoCount: number
  /** Empty when there is no open house scheduled. */
  openHouse: string[]
  primaryPhoto: string
}

export interface TourStop {
  order: string
  listingId: string
  listingStatus: ListingStatus
  address: string
  brokerTour: boolean
  openHouse: boolean
  /** `null` until the stop is scheduled. */
  time: string | null
  tourStatus: TourStopStatus
  notes: string | null
  showingInstructions: string | null
  comments: string | null
}

export interface Tour {
  id: string
  clientId: string
  /** ISO `YYYY-MM-DD`. */
  date: string
  /** `null` for a tour with no stops yet. */
  startTime: string | null
  state: TourState
  stopCount: number
  driveTimeMins: number
  walkTimeMins: number
  stops: TourStop[]
}

export interface HomeImage {
  id: string
  label: string
  /** Full-size, 800×600. */
  url: string
  /** 300×200, for grids and pickers. */
  thumb: string
}

export interface SampleData {
  _meta: SampleMeta
  agents: Agent[]
  clients: Client[]
  savedSearches: SavedSearch[]
  listings: Listing[]
  tours: Tour[]
  homeImageLibrary: HomeImage[]
}

// The JSON import is structurally inferred (heterogeneous records widen awkwardly
// under `strict`), so assert it to the declared shape once, here.
const data = raw as unknown as SampleData

export const META: SampleMeta = data._meta
export const AGENTS: Agent[] = data.agents
export const CLIENTS: Client[] = data.clients
export const SAVED_SEARCHES: SavedSearch[] = data.savedSearches
export const LISTINGS: Listing[] = data.listings
export const TOURS: Tour[] = data.tours
export const HOME_IMAGES: HomeImage[] = data.homeImageLibrary

export default data

// ─── Lookups ──────────────────────────────────────────────────────────────────

const byId = <T extends { id: string }>(rows: T[]) =>
  new Map(rows.map(row => [row.id, row]))

const AGENTS_BY_ID = byId(AGENTS)
const CLIENTS_BY_ID = byId(CLIENTS)
const LISTINGS_BY_ID = byId(LISTINGS)
const TOURS_BY_ID = byId(TOURS)

export const getAgent = (id: string): Agent | undefined => AGENTS_BY_ID.get(id)
export const getClient = (id: string): Client | undefined => CLIENTS_BY_ID.get(id)
export const getListing = (id: string): Listing | undefined => LISTINGS_BY_ID.get(id)
export const getTour = (id: string): Tour | undefined => TOURS_BY_ID.get(id)

/** The first agent — a stand-in for "the logged-in agent" in agent-facing shells. */
export const CURRENT_AGENT: Agent = AGENTS[0]

export const clientsForAgent = (agentId: string): Client[] =>
  CLIENTS.filter(c => c.agentId === agentId)

export const toursForClient = (clientId: string): Tour[] =>
  TOURS.filter(t => t.clientId === clientId)

export const savedSearchesForClient = (clientId: string): SavedSearch[] =>
  SAVED_SEARCHES.filter(s => s.savedBy === clientId)

/** Searches saved by the agent rather than by a client. */
export const agentSavedSearches = (): SavedSearch[] =>
  SAVED_SEARCHES.filter(s => s.savedBy === 'agent')

export const upcomingTours = (): Tour[] =>
  TOURS.filter(t => t.state === 'Upcoming').sort((a, b) => a.date.localeCompare(b.date))

export const pastTours = (): Tour[] =>
  TOURS.filter(t => t.state === 'Past').sort((a, b) => b.date.localeCompare(a.date))

export const listingsByStatus = (status: ListingStatus): Listing[] =>
  LISTINGS.filter(l => l.status === status)

export const openHouseListings = (): Listing[] =>
  LISTINGS.filter(l => l.openHouse.length > 0)

/** Listings whose current price is below their first recorded price. */
export const priceDropListings = (): Listing[] =>
  LISTINGS.filter(l => l.priceHistory.length > 0 && l.price < l.priceHistory[0].price)

/**
 * A stable image from the library for any key — same key always gets the same
 * image. Use for surfaces that need a photo but have no listing behind them.
 */
export const imageForKey = (key: string): HomeImage => {
  let hash = 0
  for (let i = 0; i < key.length; i++) hash = (hash * 31 + key.charCodeAt(i)) | 0
  return HOME_IMAGES[Math.abs(hash) % HOME_IMAGES.length]
}

/** The stops of a tour, joined to their full listing records where they resolve. */
export const tourStopsWithListings = (
  tour: Tour,
): Array<TourStop & { listing: Listing | undefined }> =>
  tour.stops.map(stop => ({ ...stop, listing: getListing(stop.listingId) }))

// ─── Formatters ───────────────────────────────────────────────────────────────

/** `615000` → `"$615,000"`. */
export const formatPrice = (price: number): string =>
  `$${price.toLocaleString('en-US')}`

/** `615000` → `"$615K"`, `1130000` → `"$1.13M"`. For dense cards and chips. */
export const formatPriceShort = (price: number): string => {
  if (price >= 1_000_000) return `$${(price / 1_000_000).toFixed(2).replace(/\.?0+$/, '')}M`
  if (price >= 1_000) return `$${Math.round(price / 1_000)}K`
  return `$${price}`
}

/** `2` full + `1` half → `2.5`. Half baths count as `.5`, per MLS convention. */
export const formatBaths = (listing: Listing): number =>
  listing.bathsFull + listing.bathsHalf * 0.5

/** `"142 Larkspur Ave, Rivertown, ST 00101"`. */
export const formatAddress = (listing: Listing): string =>
  `${listing.address.line1}, ${listing.address.city}, ${listing.address.state} ${listing.address.zip}`

/** `"Rivertown, ST 00101"` — the second line of a two-line address block. */
export const formatCityLine = (listing: Listing): string =>
  `${listing.address.city}, ${listing.address.state} ${listing.address.zip}`

/** `"2 bd · 1 ba · 1,015 sqft"`. Omits sqft when the listing has none. */
export const formatListingMeta = (listing: Listing): string => {
  const parts = [`${listing.beds} bd`, `${formatBaths(listing)} ba`]
  if (listing.sqft !== null) parts.push(`${listing.sqft.toLocaleString('en-US')} sqft`)
  return parts.join(' · ')
}

/** `["AB"]` → `"AB"`, `["JC","MC"]` → `"JC"` — one avatar's worth of initials. */
export const clientInitials = (client: Client): string => client.initials[0]

/** `36` → `"36 min"`, `785` → `"13 hr 5 min"`. */
export const formatMinutes = (mins: number): string => {
  if (mins < 60) return `${mins} min`
  const hours = Math.floor(mins / 60)
  const rest = mins % 60
  return rest === 0 ? `${hours} hr` : `${hours} hr ${rest} min`
}

/** `"2026-08-15"` → `"Sat, Aug 15"`. Parsed as local time, not UTC. */
export const formatTourDate = (date: string): string => {
  const [y, m, d] = date.split('-').map(Number)
  return new Date(y, m - 1, d).toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  })
}

/** `"Sat, Aug 15 | 3 Stops"` — the summary line for a tour list row. */
export const formatTourSummary = (tour: Tour): string =>
  `${formatTourDate(tour.date)} | ${tour.stopCount} ${tour.stopCount === 1 ? 'Stop' : 'Stops'}`
